{{- /*
Lucia Secret Template

This template defines the Kubernetes Secret containing sensitive configuration.
It includes:
- LLM provider API keys and credentials
- Home Assistant API token
- Database credentials

IMPORTANT: This template uses Helm's built-in secret generation capability.
In production, consider using external secret management (HashiCorp Vault, AWS Secrets Manager, etc.)
*/ -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lucia.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "lucia.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.llm.chatModel.apiKey }}
  # Chat Model API Key (base64 encoded)
  ConnectionStrings__chat-model-api-key: {{ .Values.llm.chatModel.apiKey | b64enc | quote }}
  {{- end }}

  {{- if .Values.llm.embeddingModel.apiKey }}
  # Embedding Model API Key (base64 encoded)
  ConnectionStrings__embedding-model-api-key: {{ .Values.llm.embeddingModel.apiKey | b64enc | quote }}
  {{- end }}

  {{- if .Values.homeAssistant.apiToken }}
  # Home Assistant API Token (base64 encoded)
  HomeAssistant__ApiToken: {{ .Values.homeAssistant.apiToken | b64enc | quote }}
  {{- end }}

  {{- if .Values.lucia.tlsKey }}
  # TLS Private Key (base64 encoded)
  tls.key: {{ .Values.lucia.tlsKey | b64enc | quote }}
  {{- end }}

  {{- if .Values.lucia.tlsCert }}
  # TLS Certificate (base64 encoded)
  tls.crt: {{ .Values.lucia.tlsCert | b64enc | quote }}
  {{- end }}

  {{- if .Values.lucia.otherSecrets }}
  # Additional secrets (custom key-value pairs)
  {{- range $key, $value := .Values.lucia.otherSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}

stringData:
  # Note: stringData values are automatically base64 encoded by Kubernetes
  # Use this section for non-base64 encoded values if needed

---
# ServiceAccount Secret (for internal use - auto-created by Kubernetes)
# This section is typically auto-managed, but shown here for reference
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lucia.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "lucia.labels" . | nindent 4 }}
