bind 127.0.0.1
protected-mode yes
port 6379
daemonize no
supervised no
logfile ""
dir /var/lib/lucia/redis
dbfilename dump.rdb
appendonly yes
appenddirname appendonlydir
appendfsync everysec
aof-use-rdb-preamble yes
stop-writes-on-bgsave-error yes
maxmemory-policy noeviction
maxmemory 512mb
