apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lucia
  namespace: lucia
  labels:
    app.kubernetes.io/name: lucia
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lucia
  minReplicas: 2
  maxReplicas: 5
  metrics:
    # CPU-based scaling
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    
    # Memory-based scaling
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  
  # Scaling behavior
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
        - type: Pods
          value: 2
          periodSeconds: 15
      selectPolicy: Max
