<#
.SYNOPSIS
    Exports a snapshot of Home Assistant entity states and area mappings for use
    as test fixture data in the lucia evaluation test suite.

.DESCRIPTION
    Connects to a Home Assistant instance via its REST API, pulls entity states
    for lights, media players, and switches, fetches area-to-entity mappings,
    and writes a single JSON file that FakeHomeAssistantClient can load at test
    time.  Re-run this script whenever your HA topology changes (new devices,
    renamed areas, etc.) to keep test fixtures current.

.PARAMETER Endpoint
    The base URL of the Home Assistant instance (e.g. http://homeassistant.local:8123).
    Defaults to the HA_ENDPOINT environment variable.

.PARAMETER Token
    A long-lived access token generated in HA → Profile → Long-Lived Access Tokens.
    Defaults to the HA_TOKEN environment variable.

.PARAMETER OutputPath
    Destination path for the snapshot JSON.  Defaults to
    lucia.Tests/TestData/ha-snapshot.json relative to the repo root.

.EXAMPLE
    .\scripts\Export-HomeAssistantSnapshot.ps1 `
        -Endpoint http://homeassistant.local:8123 `
        -Token "eyJhbGci..."
#>

[CmdletBinding()]
param(
    [Parameter()]
    [string] $Endpoint = $env:HA_ENDPOINT,

    [Parameter()]
    [string] $Token = $env:HA_TOKEN,

    [string] $OutputPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

if (-not $Endpoint) { throw "HA endpoint required. Set -Endpoint or the HA_ENDPOINT environment variable." }
if (-not $Token)    { throw "HA token required. Set -Token or the HA_TOKEN environment variable." }

# ── Resolve output path ────────────────────────────────────────────────
if (-not $OutputPath) {
    $repoRoot = git rev-parse --show-toplevel 2>$null
    if (-not $repoRoot) { $repoRoot = Split-Path -Parent $PSScriptRoot }
    $OutputPath = Join-Path $repoRoot 'lucia.Tests' 'TestData' 'ha-snapshot.json'
}

$outputDir = Split-Path -Parent $OutputPath
if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

# ── Helpers ─────────────────────────────────────────────────────────────
$baseUrl = $Endpoint.TrimEnd('/')
$headers = @{
    'Authorization' = "Bearer $Token"
    'Content-Type'  = 'application/json'
}

function Invoke-HaApi {
    param(
        [string] $Method = 'Get',
        [string] $Path,
        [string] $Body
    )
    $uri = "$baseUrl$Path"
    $params = @{ Uri = $uri; Headers = $headers; Method = $Method }
    if ($Body) { $params['Body'] = $Body; $params['ContentType'] = 'application/json' }
    
    $response = Invoke-WebRequest @params -UseBasicParsing
    return $response.Content | ConvertFrom-Json
}

# ── 1. Fetch all entity states ──────────────────────────────────────────
Write-Host '[1/3] Fetching entity states...' -ForegroundColor Cyan
$allStates = Invoke-HaApi -Path '/api/states'
Write-Host "       Total entities: $($allStates.Count)"

# ── 2. Filter relevant entities ─────────────────────────────────────────
Write-Host '[2/3] Filtering lights, switches, and media players...' -ForegroundColor Cyan

$lights = @($allStates | Where-Object {
    $_.entity_id -like 'light.*' -or
    ($_.entity_id -like 'switch.*' -and $_.attributes.friendly_name -like '*light*')
})

$mediaPlayers = @($allStates | Where-Object {
    $_.entity_id -like 'media_player.*'
})

Write-Host "       Lights: $($lights.Count)"
Write-Host "       Media players: $($mediaPlayers.Count)"

# ── 3. Fetch area-entity mappings ────────────────────────────────────────
Write-Host '[3/3] Fetching area mappings...' -ForegroundColor Cyan

# Template mirrors the one used by LightControlSkill.RefreshLightCacheAsync,
# but also includes area_name for human readability.
$areaTemplate = @'
[{% for id in areas() %}{% if not loop.first %}, {% endif %}{"area_id":"{{ id }}","area_name":"{{ area_name(id) }}","entities":[{% for e in area_entities(id) %}{% if not loop.first %}, {% endif %}"{{ e }}"{% endfor %}]}{% endfor %}]
'@

$areas = Invoke-HaApi -Method 'Post' -Path '/api/template' -Body (@{ template = $areaTemplate } | ConvertTo-Json)
Write-Host "       Areas: $($areas.Count)"

# ── Build snapshot ──────────────────────────────────────────────────────
$buildEntity = {
    param($entity)
    @{
        entity_id    = $entity.entity_id
        state        = $entity.state
        attributes   = $entity.attributes
        last_changed = $entity.last_changed
        last_updated = $entity.last_updated
    }
}

$snapshot = [ordered]@{
    '_comment'      = 'Auto-generated by Export-HomeAssistantSnapshot.ps1 — do not edit manually.'
    'exported_at'   = (Get-Date -Format 'o')
    'lights'        = @($lights | ForEach-Object { & $buildEntity $_ })
    'media_players' = @($mediaPlayers | ForEach-Object { & $buildEntity $_ })
    'areas'         = @($areas | ForEach-Object {
        [ordered]@{
            area_id   = $_.area_id
            area_name = $_.area_name
            entities  = @($_.entities)
        }
    })
}

# ── Write JSON ──────────────────────────────────────────────────────────
$json = $snapshot | ConvertTo-Json -Depth 10
[System.IO.File]::WriteAllText($OutputPath, $json, [System.Text.Encoding]::UTF8)

Write-Host ''
Write-Host "Snapshot written to: $OutputPath" -ForegroundColor Green
Write-Host "  Lights:        $($lights.Count)"
Write-Host "  Media players: $($mediaPlayers.Count)"
Write-Host "  Areas:         $($areas.Count)"
Write-Host ''
Write-Host 'Run this script again whenever your Home Assistant topology changes.' -ForegroundColor DarkGray
