using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using System.Text.Encodings.Web;
using Microsoft.AspNetCore.Authentication;
using Microsoft.Extensions.Options;

namespace lucia.AgentHost.Auth;

/// <summary>
/// Authentication handler that validates a platform-injected Bearer token
/// for internal service-to-service communication (agent → registry).
/// The token is generated by the Aspire AppHost and injected as an
/// environment variable into all trusted services.
/// </summary>
public sealed class InternalTokenAuthenticationHandler(
    IOptionsMonitor<InternalTokenOptions> tokenOptions,
    IOptionsMonitor<AuthenticationSchemeOptions> options,
    ILoggerFactory logger,
    UrlEncoder encoder)
    : AuthenticationHandler<AuthenticationSchemeOptions>(options, logger, encoder)
{
    protected override Task<AuthenticateResult> HandleAuthenticateAsync()
    {
        var expectedToken = tokenOptions.CurrentValue.Token;

        if (string.IsNullOrWhiteSpace(expectedToken))
        {
            return Task.FromResult(AuthenticateResult.NoResult());
        }

        var authHeader = Request.Headers.Authorization.ToString();

        if (string.IsNullOrWhiteSpace(authHeader) ||
            !authHeader.StartsWith("Bearer ", StringComparison.OrdinalIgnoreCase))
        {
            return Task.FromResult(AuthenticateResult.NoResult());
        }

        var token = authHeader["Bearer ".Length..].Trim();

        // Use constant-time comparison via SHA-256 hashes to prevent timing attacks.
        // Hashing both sides produces equal-length spans for FixedTimeEquals
        // and avoids leaking length information via an early-out branch.
        var tokenHash = SHA256.HashData(Encoding.UTF8.GetBytes(token));
        var expectedHash = SHA256.HashData(Encoding.UTF8.GetBytes(expectedToken));

        if (!CryptographicOperations.FixedTimeEquals(tokenHash, expectedHash))
        {
            return Task.FromResult(AuthenticateResult.Fail("Invalid internal token."));
        }

        var claims = new[]
        {
            new Claim(ClaimTypes.NameIdentifier, "internal-service"),
            new Claim(ClaimTypes.Name, "InternalService"),
            new Claim("auth_method", "internal_token"),
        };

        var identity = new ClaimsIdentity(claims, InternalTokenDefaults.AuthenticationScheme);
        var principal = new ClaimsPrincipal(identity);
        var ticket = new AuthenticationTicket(principal, InternalTokenDefaults.AuthenticationScheme);

        return Task.FromResult(AuthenticateResult.Success(ticket));
    }
}
