using lucia.Agents.Orchestration.Models;
using lucia.Agents.Training.Models;

namespace lucia.Agents.Orchestration;

/// <summary>
/// Observer interface for capturing intermediate orchestration pipeline events.
/// Implementations receive callbacks at each stage of the Router → Dispatch → Aggregator
/// workflow, enabling evaluation tests to inspect routing decisions, per-agent responses,
/// and aggregated results without changing the production return type.
/// <para>
/// A <c>requestId</c> is generated by <see cref="OnRequestStartedAsync"/> and must be
/// threaded through all subsequent calls so implementations can correlate events without
/// relying on <see cref="System.Threading.AsyncLocal{T}"/>, which does not survive
/// the MAF <c>InProcessExecution</c> workflow boundary.
/// </para>
/// </summary>
public interface IOrchestratorObserver
{
    /// <summary>
    /// Called before the workflow begins to initialize per-request tracking state.
    /// Returns a request ID that callers must pass to all subsequent observer methods.
    /// </summary>
    /// <param name="userRequest">The original user request text.</param>
    /// <param name="conversationHistory">Prior conversation turns for multi-turn context.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A request-scoped correlation ID for use in subsequent calls.</returns>
    Task<string> OnRequestStartedAsync(
        string userRequest,
        IReadOnlyList<TracedMessage>? conversationHistory = null,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Called after the router has selected an agent (or agents) for the request.
    /// </summary>
    /// <param name="requestId">Correlation ID returned by <see cref="OnRequestStartedAsync"/>.</param>
    /// <param name="result">The routing decision including agent ID, confidence, reasoning, and additional agents.</param>
    /// <param name="systemPrompt">The system prompt used by the router for this decision.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    Task OnRoutingCompletedAsync(
        string requestId,
        AgentChoiceResult result,
        string? systemPrompt = null,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Called after each individual agent has completed (or failed) execution.
    /// May be invoked multiple times if the router selected additional agents.
    /// </summary>
    /// <param name="requestId">Correlation ID returned by <see cref="OnRequestStartedAsync"/>.</param>
    /// <param name="response">The agent's execution result including content, success status, and timing.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    Task OnAgentExecutionCompletedAsync(string requestId, OrchestratorAgentResponse response, CancellationToken cancellationToken = default);

    /// <summary>
    /// Called after the result aggregator has composed the final response from all agent outputs.
    /// </summary>
    /// <param name="requestId">Correlation ID returned by <see cref="OnRequestStartedAsync"/>.</param>
    /// <param name="aggregatedResponse">The final aggregated text response.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    Task OnResponseAggregatedAsync(string requestId, string aggregatedResponse, CancellationToken cancellationToken = default);
}
