name: Validate

on:
  push:
    branches:
      - main
    paths:
      - 'custom_components/**'
  pull_request:
    paths:
      - 'custom_components/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
          ignore: brands
      - name: hassfest validate
        uses: home-assistant/actions/hassfest@master
